In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [ ]:
df = pd.read_csv("heart_disease.csv")
df

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,...,Yes,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,Yes,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes

In [ ]:
df.isna().sum()

Age                       29
Gender                    19
Blood Pressure            19
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

In [ ]:
df[df['Age'].isna()]

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
716,NaN,Male,160.0,184.0,Low,No,Yes,Yes,27.047567,Yes,...,Yes,NaN,Low,9.934741,High,350.0,150.0,11.272342,14.699716,No
1017,NaN,Male,173.0,251.0,Medium,No,No,No,22.763765,Yes,...,No,NaN,Medium,9.993930,Medium,280.0,159.0,14.503787,7.710791,No
1039,NaN,Female,154.0,274.0,High,No,Yes,No,35.849791,No,...,Yes,High,High,9.664409,Low,381.0,95.0,14.439670,14.609873,No
1468,NaN,Male,141.0,154.0,Medium,Yes,Yes,No,31.140165,No,...,Yes,Low,Low,6.201681,Low,329.0,137.0,12.462463,12.089437,No
1703,NaN,Male,147.0,258.0,High,Yes,Yes,No,35.350381,Yes,...,No,Low,High,8.594565,Low,323.0,96.0,11.595321,18.067759,No
1867,NaN,Male,142.0,225.0,High,Yes,No,Yes,23.275787,Yes,...,Yes,Low,Medium,6.317396,Low,329.0,85.0,7.686572,11.632494,No
2751,NaN,Male,142.0,167.0,Medium,Yes,Yes,Yes,39.995797,Yes,...,No,NaN,High,6.992129,Low,290.0,98.0,6.087670,17.357159,No
2869,NaN,Female,149.0,216.0,Low,Yes,No,No,22.739004,No,...,No,NaN,Low,8.105417,High,158.0,108.0,6.105748,18.420638,No
3195,NaN,Male,151.0,284.0,Medium,Yes,Yes,Yes,29.943396,No,...,No,Medium,Medium,9.378915,High,324.0,88.0,7.633548,13.992860,No
3265,NaN,Female,163.0,273.0,Medium,Yes,Yes,No,28.587588,Yes,...,Yes,Low,High,6.849657,Low,291.0,98.0,14.261332,6.605307,No
4071,NaN,Female,180.0,173.0,Medium,Yes,Yes,No,21.561825,No,...,Yes,Low,High,6.390804,Medium,210.0,124.0,7.838418,16.673293,No
4368,NaN,Male,167.0,188.0,High,Yes,No,No,24.582115,Yes,...,No,High,High,6.686355,Medium,192.0,92.0,12.657319,10.217309,No
4926,NaN,Male,125.0,198.0,Medium,Yes,No,No,22.952618,Yes,...,No,Low,High,4.381670,Low,207.0,150.0,3.562116,13.117695,No
5115,NaN,Female,179.0,256.0,High,No,No,No,35.562938,Yes,...,No,NaN,Low,6.955291,High,386.0,150.0,5.385226,10.895508,No
5151,NaN,Female,142.0,227.0,Low,No,No,No,18.830663,No,...,Yes,NaN,High,9.315764,Low,154.0,103.0,6.183026,5.967743,No
5396,NaN,Male,141.0,284.0,Medium,Yes,No,No,37.439024,Yes,...,Yes,Low,Medium,6.090322,Low,389.0,116.0,2.854775,11.296390,No
5857,NaN,Female,146.0,238.0,Medium,Yes,No,No,38.167391,No,...,No,High,Medium,9.726297,Medium,216.0,105.0,8.862839,19.282571,No
6143,NaN,Male,180.0,250.0,Low,Yes,Yes,No,22.749875,Yes,...,Yes,NaN,Medium,8.283050,High,104.0,91.0,3.102990,9.984202,No
6382,NaN,Male,145.0,201.0,High,No,No,No,36.778127,No,...,No,NaN,Low,4.114186,High,331.0,132.0,13.865621,5.178233,No
6477,NaN,Male,155.0,261.0,Low,No,No,Yes,38.986131,Yes,...,No,High,Medium,5.830971,Medium,370.0,150.0,14.419908,6.700846,No
6783,NaN,Female,148.0,158.0,High,Yes,Yes,Yes,39.177213,Yes,...,Yes,High,Medium,8.868347,High,124.0,86.0,10.926762,6.801805,No
7301,NaN,Female,120.0,169.0,High,Yes,No,Yes,25.504964,No,...,Yes,NaN,Low,5.916332,High,278.0,121.0,3.563080,6.087199,No
7527,NaN,Female,147.0,174.0,Medium,Yes,No,No,27.856518,Yes,...,Yes,NaN,Medium,4.687356,High,255.0,154.0,12.298738,13.056550,No
7728,NaN,Female,145.0,174.0,Medium,No,No,No,18.495778,Yes,...,No,High,Low,4.013310,High,333.0,122.0,2.373934,9.234120,No
7781,NaN,Male,170.0,297.0,High,Yes,Yes,Yes,29.746500,No,...,Yes,Medium,Medium,9.608564,High,198.0,152.0,1.236847,5.419517,No
8096,NaN,Female,167.0,255.0,Low,Yes,No,Yes,21.170543,Yes,...,Yes,High,Low,5.814622,Low,259.0,146.0,13.834235,6.571731,Yes
9192,NaN,Male,153.0,234.0,High,Yes,Yes,No,35.182266,Yes,...,No,Low,Low,7.083403,Low,387.0,122.0,9.533345,18.100440,Yes
9268,NaN,Female,139.0,184.0,High,No,No,Yes,39.398573,No,...,No,NaN,Low,5.868419,High,122.0,132.0,12.774543,9.703906,Yes
9835,NaN,Female,176.0,230.0,Low,Yes,Yes,No,30.283088,Yes,...,Yes,Medium,Medium,4.333238,Medium,191.0,158.0,11.919513,14.096972,Yes

In [ ]:
df['Age'].fillna(df['Age'].median(), inplace=True)

/tmp/ipykernel_19311/1933487976.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

In [ ]:
df['Age'].isna().sum()

np.int64(0)

In [ ]:
df.isna().sum()

Age                        0
Gender                    19
Blood Pressure            19
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

In [ ]:
df['Gender'].unique()

array(['Male', 'Female', nan], dtype=object)

In [ ]:
df['Gender'].replace('NaN', np.nan, inplace = True)

/tmp/ipykernel_19311/2139487679.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].replace('NaN', np.nan, inplace = True)

In [ ]:
df['Gender'].replace(0, np.nan, inplace = True)

/tmp/ipykernel_19311/996270185.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].replace(0, np.nan, inplace = True)

In [ ]:
df['Gender'].isna().sum()

np.int64(19)

In [ ]:
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

/tmp/ipykernel_19311/3657246551.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

In [ ]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
df['Gender'].replace({'Male':0, 'Female':1}, inplace=True)

/tmp/ipykernel_19311/3683457849.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'].replace({'Male':0, 'Female':1}, inplace=True)

In [ ]:
df['Gender'].isna().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   10000 non-null  float64
 1   Gender                10000 non-null  int64
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object
 5   Smoking               9975 non-null   object
 6   Family Heart Disease  9979 non-null   object
 7   Diabetes              9970 non-null   object
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object
 10  Low HDL Cholesterol   9975 non-null   object
 11  High LDL Cholesterol  9974 non-null   object
 12  Alcohol Consumption   7414 non-null   object
 13  Stress Level          9978 non-null   object
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   object
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), int64(1), object(11)
memory usage: 1.6+ MB

In [ ]:
df.isna().sum()

Age                        0
Gender                     0
Blood Pressure            19
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

In [ ]:
df['Blood Pressure'].median()

150.0

In [ ]:
df[df['Blood Pressure'].isna()]

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
86,67.0,1,NaN,243.0,Medium,No,No,Yes,36.929749,Yes,...,Yes,Low,Medium,7.104835,Medium,383.0,100.0,11.984273,10.168021,No
223,62.0,1,NaN,231.0,Medium,Yes,Yes,No,28.961550,Yes,...,Yes,NaN,High,9.771211,High,150.0,97.0,5.222643,12.288388,No
302,61.0,1,NaN,279.0,Low,Yes,Yes,No,21.746595,Yes,...,Yes,Medium,Low,5.393680,Medium,190.0,143.0,7.542982,6.426180,No
309,72.0,1,NaN,151.0,Low,No,Yes,Yes,26.835496,Yes,...,Yes,NaN,Medium,6.554749,Medium,367.0,94.0,13.357922,19.620655,No
608,72.0,0,NaN,280.0,Medium,No,No,No,39.818485,No,...,Yes,NaN,Low,7.006837,Low,290.0,112.0,0.648018,14.781755,No
1410,61.0,1,NaN,224.0,High,No,Yes,Yes,35.976633,Yes,...,Yes,NaN,High,8.705024,Medium,235.0,138.0,7.428157,11.089096,No
3076,33.0,1,NaN,162.0,High,Yes,No,No,38.157967,Yes,...,No,Medium,Medium,4.531113,Medium,115.0,139.0,12.081217,17.174314,No
3175,55.0,0,NaN,161.0,Medium,Yes,No,Yes,29.301913,No,...,Yes,Medium,High,8.041602,Low,162.0,124.0,11.709375,9.847357,No
3194,40.0,1,NaN,262.0,Medium,Yes,No,Yes,23.654700,No,...,No,Low,Low,5.475813,Medium,200.0,116.0,13.054987,12.184590,No
4481,44.0,1,NaN,289.0,Medium,No,Yes,No,34.846461,No,...,Yes,High,Low,5.490190,Low,373.0,83.0,11.585405,11.366388,No
4931,52.0,1,NaN,280.0,Low,Yes,No,Yes,19.043459,No,...,No,Low,High,7.861050,High,306.0,82.0,13.072224,14.961158,No
5110,76.0,1,NaN,288.0,Medium,Yes,Yes,Yes,38.146850,Yes,...,Yes,Low,Low,6.971219,Low,285.0,136.0,14.826679,13.713214,No
5155,26.0,0,NaN,203.0,Medium,No,Yes,No,31.035658,Yes,...,No,High,Medium,7.753860,High,257.0,93.0,5.044774,13.639213,No
7302,53.0,1,NaN,260.0,Low,No,Yes,No,28.177217,No,...,No,NaN,Medium,4.842046,High,139.0,97.0,2.876875,10.404755,No
7913,68.0,0,NaN,263.0,Medium,Yes,No,No,27.440483,Yes,...,Yes,Medium,Low,9.229506,Low,331.0,90.0,12.715799,19.581150,No
8067,49.0,0,NaN,200.0,Medium,Yes,No,No,18.952767,Yes,...,Yes,Medium,Medium,5.922086,Low,357.0,152.0,3.140954,10.853419,Yes
8453,49.0,1,NaN,263.0,Medium,No,No,Yes,34.121430,No,...,No,Low,Medium,8.470164,Medium,373.0,129.0,12.506141,9.276524,Yes
8660,73.0,0,NaN,269.0,High,No,Yes,No,23.953984,No,...,Yes,Medium,High,9.738422,Medium,358.0,80.0,5.209644,10.514395,Yes
9360,60.0,1,NaN,202.0,Medium,Yes,No,No,18.312554,No,...,Yes,High,High,4.504033,Low,287.0,146.0,4.937594,9.109753,Yes

In [ ]:
df['Blood Pressure'].unique()

array([153., 146., 126., 122., 166., 152., 121., 161., 135., 144., 179.,
       134., 143., 150., 133., 173., 125., 136., 137., 139., 170., 159.,
       158., 171., 151., 163., 128., 165., 129., 168., 155., 142., 127.,
       132., 176., 141., 160., 154., 164., 138., 149., 178., 140., 147.,
        nan, 175., 162., 157., 174., 123., 145., 124., 148., 169., 172.,
       167., 131., 120., 177., 130., 180., 156.])

In [ ]:
df['Blood Pressure'].fillna(df['Blood Pressure'].median(), inplace=True)

/tmp/ipykernel_19311/3000306976.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Blood Pressure'].fillna(df['Blood Pressure'].median(), inplace=True)

In [ ]:
df['Blood Pressure'].unique()

array([153., 146., 126., 122., 166., 152., 121., 161., 135., 144., 179.,
       134., 143., 150., 133., 173., 125., 136., 137., 139., 170., 159.,
       158., 171., 151., 163., 128., 165., 129., 168., 155., 142., 127.,
       132., 176., 141., 160., 154., 164., 138., 149., 178., 140., 147.,
       175., 162., 157., 174., 123., 145., 124., 148., 169., 172., 167.,
       131., 120., 177., 130., 180., 156.])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   10000 non-null  float64
 1   Gender                10000 non-null  int64
 2   Blood Pressure        10000 non-null  float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object
 5   Smoking               9975 non-null   object
 6   Family Heart Disease  9979 non-null   object
 7   Diabetes              9970 non-null   object
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object
 10  Low HDL Cholesterol   9975 non-null   object
 11  High LDL Cholesterol  9974 non-null   object
 12  Alcohol Consumption   7414 non-null   object
 13  Stress Level          9978 non-null   object
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   object
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), int64(1), object(11)
memory usage: 1.6+ MB

In [ ]:
df.isna().sum()

Age                        0
Gender                     0
Blood Pressure             0
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

In [ ]:
df['Cholesterol Level'].median()

226.0

In [ ]:
df['Cholesterol Level'].unique()

array([155., 286., 216., 293., 242., 257., 175., 187., 291., 252., 191.,
       296., 215., 290., 255., 245., 219., 246., 268., 300., 223., 206.,
       259., 228., 185., 278., 152., 163., 183., 218., 253., 178., 197.,
       243., 266., 287., 281., 224., 177., 270., 158., 283., 272., 198.,
       240., 274., 225., 299., 298., 182., 202., 189., 167., 162., 254.,
       280., 151., 284., 292., 288., 277., 176., 170., 157., 232., 204.,
       199., 261., 295., 179., 188., 265., 289., 208., 230., 226., 221.,
       165., 229., 201., 233., 276., 247., 267., 159., 294., 238., 153.,
       169., 193., 172., 196., 244., 271., 262., 200., 241., 161., 269.,
       212., 211., 258., 195., 160., 222.,  nan, 256., 231., 263., 168.,
       273., 235., 186., 279., 282., 213., 156., 171., 236., 184., 214.,
       192., 217., 203., 210., 260., 237., 227., 190., 205., 249., 150.,
       251., 154., 297., 194., 209., 264., 174., 248., 250., 285., 173.,
       207., 234., 166., 220., 164., 275., 239., 180., 181.])

In [ ]:
df['Cholesterol Level'].fillna(df['Cholesterol Level'].median(), inplace=True)

/tmp/ipykernel_19311/3517211859.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cholesterol Level'].fillna(df['Cholesterol Level'].median(), inplace=True)

In [ ]:
df['Cholesterol Level'].isna().sum()

np.int64(0)

In [ ]:
df.isna().sum()

Age                        0
Gender                     0
Blood Pressure             0
Cholesterol Level          0
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

In [ ]:
df['Exercise Habits'].mode()

0    High
Name: Exercise Habits, dtype: object

In [ ]:
df['Exercise Habits'].fillna('High', inplace=True)

/tmp/ipykernel_19311/1204400371.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Exercise Habits'].fillna('High', inplace=True)

In [ ]:
df['Exercise Habits'].unique()

array(['High', 'Low', 'Medium'], dtype=object)

In [ ]:
df['Exercise Habits'].replace({'High':0, 'Low':1, 'Medium':3}, inplace=True)

/tmp/ipykernel_19311/3315530220.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Exercise Habits'].replace({'High':0, 'Low':1, 'Medium':3}, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   10000 non-null  float64
 1   Gender                10000 non-null  int64
 2   Blood Pressure        10000 non-null  float64
 3   Cholesterol Level     10000 non-null  float64
 4   Exercise Habits       10000 non-null  int64
 5   Smoking               9975 non-null   object
 6   Family Heart Disease  9979 non-null   object
 7   Diabetes              9970 non-null   object
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object
 10  Low HDL Cholesterol   9975 non-null   object
 11  High LDL Cholesterol  9974 non-null   object
 12  Alcohol Consumption   7414 non-null   object
 13  Stress Level          9978 non-null   object
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   object
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), int64(2), object(10)
memory usage: 1.6+ MB

In [ ]:
df['Smoking'].unique()
# df['Family Heart Disease'].unique()
# df['Diabetes'].unique()
# df['High Blood Pressure'].unique()
# df['Low HDL Cholesterol'].unique()
# df['Family Heart Disease'].unique()
# df['High LDL Cholesterol'].unique()
# df['Alcohol Consumption'].unique()
# df['Stress Level'].unique()
# df['Sugar Consumption'].unique()

array(['Yes', 'No', nan], dtype=object)

In [ ]:
df["BMI"].fillna(df['BMI'].median(), inplace=True)

/tmp/ipykernel_19311/634756394.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["BMI"].fillna(df['BMI'].median(), inplace=True)

In [ ]:
df['Smoking'].fillna(df['Smoking'].mode()[0], inplace=True)

In [ ]:
df['Smoking'].isna().sum()

np.int64(0)

In [ ]:
df['Smoking'].unique()

array(['Yes', 'No'], dtype=object)

In [ ]:
df['Smoking'].replace({'Yes':0, 'No':1}, inplace=True)

/tmp/ipykernel_19311/406764524.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Smoking'].replace({'Yes':0, 'No':1}, inplace=True)

In [ ]:
df['Family Heart Disease'].unique()

array(['Yes', 'No', nan], dtype=object)

In [ ]:
df['Family Heart Disease'].fillna(df['Family Heart Disease'].mode()[0], inplace=True)

/tmp/ipykernel_19311/2127529142.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Family Heart Disease'].fillna(df['Family Heart Disease'].mode()[0], inplace=True)

In [ ]:
df['Family Heart Disease'].replace({'Yes':0, 'No':1}, inplace=True)

/tmp/ipykernel_19311/3269634786.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Family Heart Disease'].replace({'Yes':0, 'No':1}, inplace=True)

In [ ]:
df['Diabetes'].unique()

array(['No', 'Yes', nan], dtype=object)

In [ ]:
df['Diabetes'].fillna(df['Diabetes'].mode()[0], inplace=True)

/tmp/ipykernel_19311/3045495013.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Diabetes'].fillna(df['Diabetes'].mode()[0], inplace=True)

In [ ]:
df['Diabetes'].replace({'Yes':0, 'No':1}, inplace=True)

/tmp/ipykernel_19311/4117013334.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Diabetes'].replace({'Yes':0, 'No':1}, inplace=True)

In [ ]:
df['High Blood Pressure'].unique()

array(['Yes', 'No', nan], dtype=object)

In [ ]:
df['High Blood Pressure'].fillna(df['High Blood Pressure'].mode()[0], inplace=True)

/tmp/ipykernel_19311/2654022065.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['High Blood Pressure'].fillna(df['High Blood Pressure'].mode()[0], inplace=True)

In [ ]:
df['High Blood Pressure'].replace({'Yes':0, 'No':1}, inplace=True)

/tmp/ipykernel_19311/1295962308.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['High Blood Pressure'].replace({'Yes':0, 'No':1}, inplace=True)

In [ ]:
df['Low HDL Cholesterol'].unique()

array(['Yes', 'No', nan], dtype=object)

In [ ]:
df['Low HDL Cholesterol'].fillna(df['Low HDL Cholesterol'].mode()[0], inplace=True)

/tmp/ipykernel_19311/2333082375.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Low HDL Cholesterol'].fillna(df['Low HDL Cholesterol'].mode()[0], inplace=True)

In [ ]:
df['Low HDL Cholesterol'].replace({'Yes':0, 'No':1}, inplace=True)

/tmp/ipykernel_19311/3062300607.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Low HDL Cholesterol'].replace({'Yes':0, 'No':1}, inplace=True)

In [ ]:
df['Family Heart Disease'].unique()

array(['Yes', 'No'], dtype=object)

In [ ]:
df['Family Heart Disease'].fillna(df['Family Heart Disease'].mode()[0], inplace=True)

In [ ]:
df['Family Heart Disease'].replace({'Yes':0, 'No':1}, inplace=True)

In [ ]:
df['High LDL Cholesterol'].unique()

array(['No', 'Yes', nan], dtype=object)

In [ ]:
df['High LDL Cholesterol'].fillna(df['High LDL Cholesterol'].mode()[0], inplace=True)

/tmp/ipykernel_19311/1665824344.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['High LDL Cholesterol'].fillna(df['High LDL Cholesterol'].mode()[0], inplace=True)

In [ ]:
df['High LDL Cholesterol'].replace({'Yes':0, 'No':1}, inplace=True)

/tmp/ipykernel_19311/3272452947.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['High LDL Cholesterol'].replace({'Yes':0, 'No':1}, inplace=True)

In [ ]:
df['Alcohol Consumption'].unique()

array(['High', 'Medium', 'Low', nan], dtype=object)

In [ ]:
df['Alcohol Consumption'].fillna(df['Alcohol Consumption'].mode()[0], inplace=True)

/tmp/ipykernel_19311/1630728145.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Alcohol Consumption'].fillna(df['Alcohol Consumption'].mode()[0], inplace=True)

In [ ]:
df['Alcohol Consumption'].replace({'High':0, 'Medium':1, 'Low':2}, inplace=True)

/tmp/ipykernel_19311/4061727701.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Alcohol Consumption'].replace({'High':0, 'Medium':1, 'Low':2}, inplace=True)

In [ ]:
df['Stress Level'].unique()

array(['Medium', 'High', 'Low', nan], dtype=object)

In [ ]:
df['Stress Level'].fillna(df['Stress Level'].mode()[0], inplace=True)

/tmp/ipykernel_19311/2043733895.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Stress Level'].fillna(df['Stress Level'].mode()[0], inplace=True)

In [ ]:
df['Stress Level'].replace({'High':0, 'Medium':1, 'Low':2}, inplace=True)

/tmp/ipykernel_19311/3020568637.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Stress Level'].replace({'High':0, 'Medium':1, 'Low':2}, inplace=True)

In [ ]:
df['Sugar Consumption'].unique()

array(['Medium', 'Low', 'High', nan], dtype=object)

In [ ]:
df['Sugar Consumption'].fillna(df['Sugar Consumption'].mode()[0], inplace=True)

/tmp/ipykernel_19311/335383307.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sugar Consumption'].fillna(df['Sugar Consumption'].mode()[0], inplace=True)

In [ ]:
df['Sugar Consumption'].replace({'High':0, 'Medium':1, 'Low':2}, inplace=True)

/tmp/ipykernel_19311/460224482.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Sugar Consumption'].replace({'High':0, 'Medium':1, 'Low':2}, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   10000 non-null  float64
 1   Gender                10000 non-null  int64
 2   Blood Pressure        10000 non-null  float64
 3   Cholesterol Level     10000 non-null  float64
 4   Exercise Habits       10000 non-null  int64
 5   Smoking               10000 non-null  int64
 6   Family Heart Disease  10000 non-null  int64
 7   Diabetes              10000 non-null  int64
 8   BMI                   10000 non-null  float64
 9   High Blood Pressure   10000 non-null  int64
 10  Low HDL Cholesterol   10000 non-null  int64
 11  High LDL Cholesterol  10000 non-null  int64
 12  Alcohol Consumption   10000 non-null  int64
 13  Stress Level          10000 non-null  int64
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     10000 non-null  int64
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), int64(11), object(1)
memory usage: 1.6+ MB

In [ ]:
df.isna().sum()

Age                      0
Gender                   0
Blood Pressure           0
Cholesterol Level        0
Exercise Habits          0
Smoking                  0
Family Heart Disease     0
Diabetes                 0
BMI                      0
High Blood Pressure      0
Low HDL Cholesterol      0
High LDL Cholesterol     0
Alcohol Consumption      0
Stress Level             0
Sleep Hours             25
Sugar Consumption        0
Triglyceride Level      26
Fasting Blood Sugar     22
CRP Level               26
Homocysteine Level      20
Heart Disease Status     0
dtype: int64

In [ ]:
df['Sleep Hours'].fillna(df['Sleep Hours'].median(), inplace=True)

/tmp/ipykernel_19311/4152551825.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sleep Hours'].fillna(df['Sleep Hours'].median(), inplace=True)

In [ ]:
df['Triglyceride Level'].unique()

array([342., 133., 393., 293., 263., 126., 107., 228., 317., 199., 231.,
       109., 196., 178., 343., 397., 212., 384., 346., 290., 380., 312.,
       102., 257., 180., 233., 176., 396., 179., 292., 300., 220., 341.,
       277., 248., 170., 250., 388., 120., 268., 329., 184., 377., 152.,
       378., 121., 197., 338., 187., 399., 221., 130., 110., 194., 151.,
       124., 143., 240., 118., 288., 319., 253.,  nan, 269., 278., 308.,
       224., 217., 362., 123., 116., 285., 369., 307., 375., 148., 245.,
       383., 111., 183., 296., 391., 214., 387., 249., 274., 386., 129.,
       310., 236., 222., 365., 349., 316., 283., 381., 314., 195., 229.,
       266., 360., 311., 159., 215., 139., 303., 158., 347., 227., 101.,
       140., 165., 315., 137., 128., 204., 299., 149., 167., 234., 209.,
       202., 190., 132., 389., 258., 328., 320., 279., 131., 374., 244.,
       113., 337., 203., 117., 122., 368., 331., 160., 185., 273., 340.,
       193., 255., 210., 247., 150., 213., 235., 259., 313., 271., 295.,
       366., 363., 359., 173., 136., 241., 379., 371., 115., 157., 262.,
       325., 260., 156., 302., 367., 372., 357., 304., 112., 286., 356.,
       186., 232., 332., 355., 275., 153., 230., 177., 330., 105., 146.,
       181., 106., 182., 242., 211., 174., 144., 336., 353., 164., 385.,
       301., 226., 265., 135., 339., 261., 155., 169., 166., 239., 305.,
       351., 251., 256., 207., 309., 188., 147., 370., 254., 318., 225.,
       358., 321., 350., 192., 394., 252., 294., 284., 400., 127., 154.,
       264., 208., 272., 246., 345., 171., 398., 119., 103., 145., 218.,
       382., 191., 108., 395., 392., 161., 335., 287., 297., 219., 125.,
       361., 172., 291., 141., 373., 334., 206., 298., 189., 134., 281.,
       175., 104., 344., 100., 306., 276., 322., 142., 354., 327., 376.,
       114., 205., 267., 200., 168., 223., 333., 289., 364., 162., 390.,
       198., 352., 280., 238., 326., 243., 282., 201., 324., 163., 138.,
       348., 237., 323., 270., 216.])

In [ ]:
df['Triglyceride Level'].fillna(df['Triglyceride Level'].median(), inplace=True)

/tmp/ipykernel_19311/3728582725.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Triglyceride Level'].fillna(df['Triglyceride Level'].median(), inplace=True)

In [ ]:
df['Triglyceride Level'].unique()

array([342., 133., 393., 293., 263., 126., 107., 228., 317., 199., 231.,
       109., 196., 178., 343., 397., 212., 384., 346., 290., 380., 312.,
       102., 257., 180., 233., 176., 396., 179., 292., 300., 220., 341.,
       277., 248., 170., 250., 388., 120., 268., 329., 184., 377., 152.,
       378., 121., 197., 338., 187., 399., 221., 130., 110., 194., 151.,
       124., 143., 240., 118., 288., 319., 253., 269., 278., 308., 224.,
       217., 362., 123., 116., 285., 369., 307., 375., 148., 245., 383.,
       111., 183., 296., 391., 214., 387., 249., 274., 386., 129., 310.,
       236., 222., 365., 349., 316., 283., 381., 314., 195., 229., 266.,
       360., 311., 159., 215., 139., 303., 158., 347., 227., 101., 140.,
       165., 315., 137., 128., 204., 299., 149., 167., 234., 209., 202.,
       190., 132., 389., 258., 328., 320., 279., 131., 374., 244., 113.,
       337., 203., 117., 122., 368., 331., 160., 185., 273., 340., 193.,
       255., 210., 247., 150., 213., 235., 259., 313., 271., 295., 366.,
       363., 359., 173., 136., 241., 379., 371., 115., 157., 262., 325.,
       260., 156., 302., 367., 372., 357., 304., 112., 286., 356., 186.,
       232., 332., 355., 275., 153., 230., 177., 330., 105., 146., 181.,
       106., 182., 242., 211., 174., 144., 336., 353., 164., 385., 301.,
       226., 265., 135., 339., 261., 155., 169., 166., 239., 305., 351.,
       251., 256., 207., 309., 188., 147., 370., 254., 318., 225., 358.,
       321., 350., 192., 394., 252., 294., 284., 400., 127., 154., 264.,
       208., 272., 246., 345., 171., 398., 119., 103., 145., 218., 382.,
       191., 108., 395., 392., 161., 335., 287., 297., 219., 125., 361.,
       172., 291., 141., 373., 334., 206., 298., 189., 134., 281., 175.,
       104., 344., 100., 306., 276., 322., 142., 354., 327., 376., 114.,
       205., 267., 200., 168., 223., 333., 289., 364., 162., 390., 198.,
       352., 280., 238., 326., 243., 282., 201., 324., 163., 138., 348.,
       237., 323., 270., 216.])

In [ ]:
df['Fasting Blood Sugar'].unique()

array([ nan, 157.,  92.,  94., 154.,  91.,  85., 111., 103.,  96., 139.,
       142., 102., 124., 155., 160., 132., 106., 144., 135.,  80., 116.,
       122., 146., 126., 101.,  95., 151.,  90., 104., 129.,  86.,  89.,
        84.,  82., 110., 112., 127., 134.,  99., 131.,  98.,  97., 159.,
       153., 149.,  87., 147., 114., 119., 100., 128., 130., 109., 125.,
       121., 118., 138., 140., 156., 133., 117., 141., 108., 136., 107.,
       143., 145., 152.,  88., 113., 148., 120., 150., 137.,  83.,  93.,
       105., 123., 115., 158.,  81.])

In [ ]:
df['Fasting Blood Sugar'].fillna(df['Fasting Blood Sugar'].median(), inplace=True)

/tmp/ipykernel_19311/1937788200.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fasting Blood Sugar'].fillna(df['Fasting Blood Sugar'].median(), inplace=True)

In [ ]:
df[df['CRP Level'].isna()]

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
94,21.0,1,133.0,270.0,3,0,0,1,19.229796,1,...,1,1,2,8.855077,1,110.0,127.0,NaN,17.458114,No
149,50.0,1,135.0,162.0,3,1,0,0,28.526847,0,...,0,2,1,5.219300,2,274.0,156.0,NaN,9.763854,No
187,56.0,1,169.0,274.0,0,0,0,1,25.971809,0,...,1,0,2,9.941763,2,329.0,136.0,NaN,9.303716,No
1344,79.0,1,165.0,192.0,1,0,1,1,38.043410,0,...,1,0,1,5.167275,1,250.0,138.0,NaN,9.192737,No
1421,18.0,1,123.0,295.0,3,1,0,1,30.304865,0,...,0,1,2,6.766107,1,332.0,142.0,NaN,12.589697,No
4023,41.0,0,142.0,241.0,1,1,1,1,21.916843,1,...,0,1,2,8.615786,2,310.0,106.0,NaN,10.160272,No
4623,68.0,0,164.0,159.0,0,1,1,0,19.714606,1,...,0,1,2,9.758989,2,314.0,96.0,NaN,10.555064,No
4810,39.0,0,170.0,258.0,1,1,0,0,29.898034,1,...,0,0,0,5.625716,1,269.0,86.0,NaN,18.452774,No
4981,36.0,1,155.0,226.0,0,0,1,0,25.954143,1,...,1,2,1,6.421130,2,217.0,90.0,NaN,8.708078,No
5234,33.0,0,134.0,156.0,1,1,1,1,32.944905,1,...,0,1,0,6.440661,1,284.0,139.0,NaN,18.210854,No
5418,64.0,0,164.0,256.0,1,1,1,0,19.902039,1,...,0,0,2,4.764736,2,259.0,132.0,NaN,15.005858,No
5623,37.0,0,142.0,235.0,3,0,1,0,35.939757,0,...,1,1,0,5.612441,0,290.0,95.0,NaN,18.353874,No
5997,58.0,1,131.0,254.0,1,0,0,0,30.660906,0,...,0,0,2,7.050220,0,213.0,85.0,NaN,8.356431,No
6300,33.0,0,132.0,205.0,0,1,1,1,30.634876,1,...,1,1,0,7.104969,2,284.0,133.0,NaN,10.477948,No
7167,43.0,0,138.0,282.0,0,1,0,1,35.852054,0,...,1,0,2,6.621793,0,391.0,108.0,NaN,12.605205,No
7411,78.0,1,125.0,160.0,0,0,1,1,37.503726,1,...,0,1,0,7.187817,2,155.0,92.0,NaN,13.727376,No
7583,36.0,0,169.0,243.0,0,1,1,1,34.331927,0,...,0,2,2,4.172166,2,331.0,105.0,NaN,11.740988,No
7866,46.0,0,178.0,249.0,3,0,1,0,23.706950,1,...,0,1,2,8.719044,1,320.0,110.0,NaN,7.970677,No
8027,55.0,1,142.0,288.0,0,1,0,0,26.025950,0,...,1,1,2,4.595214,2,200.0,117.0,NaN,12.493561,Yes
8033,77.0,1,120.0,273.0,3,0,0,1,34.190573,0,...,0,1,2,6.811346,1,131.0,128.0,NaN,7.913064,Yes
8631,25.0,0,161.0,248.0,0,1,1,0,38.127116,0,...,1,0,2,8.705461,1,206.0,157.0,NaN,18.547099,Yes
8701,49.0,1,132.0,278.0,1,1,1,1,24.291550,0,...,1,1,1,8.031916,1,348.0,156.0,NaN,8.219278,Yes
9052,35.0,1,126.0,191.0,3,1,0,1,24.128734,0,...,0,2,1,4.668165,0,169.0,119.0,NaN,17.163093,Yes
9234,49.0,1,141.0,173.0,1,1,1,1,31.269441,1,...,1,0,1,9.997300,2,135.0,117.0,NaN,18.566830,Yes
9548,19.0,0,173.0,161.0,1,0,1,0,22.487423,1,...,0,1,1,9.320160,2,330.0,112.0,NaN,15.812854,Yes
9925,19.0,1,134.0,216.0,3,0,0,1,19.950673,1,...,1,1,2,4.205017,1,158.0,116.0,NaN,17.970706,Yes

In [ ]:
df['CRP Level'].fillna(df['CRP Level'].median(), inplace=True)

/tmp/ipykernel_19311/1749724454.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['CRP Level'].fillna(df['CRP Level'].median(), inplace=True)

In [ ]:
df['Homocysteine Level'].unique()

array([12.3872504 , 19.29887548, 11.23092568, ...,  9.49242901,
       11.87348585,  6.20853115])

In [ ]:
df['Homocysteine Level'].fillna(df['Homocysteine Level'].median(), inplace=True)

/tmp/ipykernel_19311/474709469.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Homocysteine Level'].fillna(df['Homocysteine Level'].median(), inplace=True)

In [ ]:
df.isna().sum()

Age                     0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Exercise Habits         0
Smoking                 0
Family Heart Disease    0
Diabetes                0
BMI                     0
High Blood Pressure     0
Low HDL Cholesterol     0
High LDL Cholesterol    0
Alcohol Consumption     0
Stress Level            0
Sleep Hours             0
Sugar Consumption       0
Triglyceride Level      0
Fasting Blood Sugar     0
CRP Level               0
Homocysteine Level      0
Heart Disease Status    0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   10000 non-null  float64
 1   Gender                10000 non-null  int64
 2   Blood Pressure        10000 non-null  float64
 3   Cholesterol Level     10000 non-null  float64
 4   Exercise Habits       10000 non-null  int64
 5   Smoking               10000 non-null  int64
 6   Family Heart Disease  10000 non-null  int64
 7   Diabetes              10000 non-null  int64
 8   BMI                   10000 non-null  float64
 9   High Blood Pressure   10000 non-null  int64
 10  Low HDL Cholesterol   10000 non-null  int64
 11  High LDL Cholesterol  10000 non-null  int64
 12  Alcohol Consumption   10000 non-null  int64
 13  Stress Level          10000 non-null  int64
 14  Sleep Hours           10000 non-null  float64
 15  Sugar Consumption     10000 non-null  int64
 16  Triglyceride Level    10000 non-null  float64
 17  Fasting Blood Sugar   10000 non-null  float64
 18  CRP Level             10000 non-null  float64
 19  Homocysteine Level    10000 non-null  float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), int64(11), object(1)
memory usage: 1.6+ MB

In [ ]:
df['Heart Disease Status'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
df['Heart Disease Status'].replace({'Yes':0, 'No':1}, inplace=True)

/tmp/ipykernel_19311/2436951749.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Heart Disease Status'].replace({'Yes':0, 'No':1}, inplace=True)
/tmp/ipykernel_19311/2436951749.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Heart Disease Status'].replace({'Yes':0, 'No':1}, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   10000 non-null  float64
 1   Gender                10000 non-null  int64
 2   Blood Pressure        10000 non-null  float64
 3   Cholesterol Level     10000 non-null  float64
 4   Exercise Habits       10000 non-null  int64
 5   Smoking               10000 non-null  int64
 6   Family Heart Disease  10000 non-null  int64
 7   Diabetes              10000 non-null  int64
 8   BMI                   10000 non-null  float64
 9   High Blood Pressure   10000 non-null  int64
 10  Low HDL Cholesterol   10000 non-null  int64
 11  High LDL Cholesterol  10000 non-null  int64
 12  Alcohol Consumption   10000 non-null  int64
 13  Stress Level          10000 non-null  int64
 14  Sleep Hours           10000 non-null  float64
 15  Sugar Consumption     10000 non-null  int64
 16  Triglyceride Level    10000 non-null  float64
 17  Fasting Blood Sugar   10000 non-null  float64
 18  CRP Level             10000 non-null  float64
 19  Homocysteine Level    10000 non-null  float64
 20  Heart Disease Status  10000 non-null  int64
dtypes: float64(9), int64(12)
memory usage: 1.6 MB

In [ ]:
df

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,0,153.0,155.0,0,0,0,1,24.991591,0,...,1,0,1,7.633228,1,342.0,120.0,12.969246,12.387250,1
1,69.0,1,146.0,286.0,0,1,0,0,25.221799,1,...,1,1,0,8.744034,1,133.0,157.0,9.355389,19.298875,1
2,46.0,0,126.0,216.0,1,1,1,1,29.855447,1,...,0,2,2,4.440440,2,393.0,92.0,12.709873,11.230926,1
3,32.0,1,122.0,293.0,0,0,0,1,24.130477,0,...,0,2,0,5.249405,0,293.0,94.0,12.509046,5.961958,1
4,60.0,0,166.0,242.0,1,0,0,0,20.486289,0,...,1,2,0,7.030971,0,263.0,154.0,10.381259,8.153887,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,1,136.0,243.0,3,0,1,1,18.788791,0,...,0,1,0,6.834954,1,343.0,133.0,3.588814,19.132004,0
9996,38.0,0,172.0,154.0,3,1,1,1,31.856801,0,...,0,1,0,8.247784,2,377.0,83.0,2.658267,9.715709,0
9997,73.0,0,152.0,201.0,0,0,1,0,26.899911,1,...,0,1,2,4.436762,2,248.0,88.0,4.408867,9.492429,0
9998,23.0,0,142.0,299.0,1,0,1,0,34.964026,0,...,0,1,0,8.526329,1,113.0,153.0,7.215634,11.873486,0
9999,38.0,1,128.0,193.0,3,0,0,0,25.111295,1,...,0,0,1,5.659394,0,121.0,149.0,14.387810,6.208531,0

In [ ]:
x = df.drop('Heart Disease Status', axis =1)
y = df['Heart Disease Status']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

In [ ]:
rf_model = RandomForestClassifier()
rf_model.fit(x_train, y_train)

RandomForestClassifier()

In [ ]:
y_pred = rf_model.predict(x_test)
y_pred[:5]

array([1, 1, 1, 1, 1])

In [ ]:
y_test[:5]

9953    0
3850    1
4962    1
3886    1
5437    1
Name: Heart Disease Status, dtype: int64

In [ ]:
# testing

conf_mat = confusion_matrix(y_test, y_pred)
print("Condusion Matrx", confusion_matrix)

acc_score = accuracy_score(y_test, y_pred)
print("Accuracy Score", acc_score)

class_report = classification_report(y_test, y_pred)
print("Classification Report", class_report)

Condusion Matrx <function confusion_matrix at 0x7fccd5d31260>
Accuracy Score 0.8083333333333333
Classification Report               precision    recall  f1-score   support

           0       0.00      0.00      0.00       574
           1       0.81      1.00      0.89      2426

    accuracy                           0.81      3000
   macro avg       0.40      0.50      0.45      3000
weighted avg       0.65      0.81      0.72      3000

In [ ]:
# training

y_train_pred = rf_model.predict(x_train)

conf_mat = confusion_matrix(y_train, y_train_pred)
print("Condusion Matrx", confusion_matrix)

acc_score = accuracy_score(y_train, y_train_pred)
print("Accuracy Score", acc_score)

class_report = classification_report(y_train, y_train_pred)
print("Classification Report", class_report)

Condusion Matrx <function confusion_matrix at 0x7fccd5d31260>
Accuracy Score 1.0
Classification Report               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1426
           1       1.00      1.00      1.00      5574

    accuracy                           1.00      7000
   macro avg       1.00      1.00      1.00      7000
weighted avg       1.00      1.00      1.00      7000

# Hyper Parameter Tuning

In [ ]:
rf_model = RandomForestClassifier()

parameters = {'criterion': ["gini"],
              'max_depth': np.arange(2, 6),
              'min_samples_split': np.arange(3,8),
              'min_samples_leaf': np.arange(1,5)}

In [ ]:
gscv = GridSearchCV(rf_model, parameters, cv=5)
gscv.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini'],
                         'max_depth': array([2, 3, 4, 5]),
                         'min_samples_leaf': array([1, 2, 3, 4]),
                         'min_samples_split': array([3, 4, 5, 6, 7])})

In [ ]:
rf_hymodel = RandomForestClassifier(max_depth=np.int64(2), min_samples_leaf=np.int64(1),
                       min_samples_split=np.int64(3))
rf_hymodel.fit(x_train, y_train)

RandomForestClassifier(max_depth=np.int64(2), min_samples_leaf=np.int64(1),
                       min_samples_split=np.int64(3))

In [ ]:
y_pred = rf_hymodel.predict(x_test)
y_pred[:5]

array([1, 1, 1, 1, 1])

In [ ]:
y_test[:5]

9953    0
3850    1
4962    1
3886    1
5437    1
Name: Heart Disease Status, dtype: int64

In [ ]:
#testing

con_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix", con_mat)

acc_score = accuracy_score(y_test, y_pred)
print("Acuuracy Score", acc_score)

class_report = classification_report(y_test, y_pred)
print("Classification Report", class_report)

Confusion Matrix [[   0  574]
 [   0 2426]]
Acuuracy Score 0.8086666666666666
Classification Report               precision    recall  f1-score   support

           0       0.00      0.00      0.00       574
           1       0.81      1.00      0.89      2426

    accuracy                           0.81      3000
   macro avg       0.40      0.50      0.45      3000
weighted avg       0.65      0.81      0.72      3000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
#training

y_Pred_train = rf_hymodel.predict(x_train)

con_mat = confusion_matrix(y_train, y_Pred_train)
print("Confusion Matrix", con_mat)

acc_score = accuracy_score(y_train, y_Pred_train)
print("Acuuracy Score", acc_score)

class_report = classification_report(y_train, y_Pred_train)
print("Classification Report", class_report)

Confusion Matrix [[   0 1426]
 [   0 5574]]
Acuuracy Score 0.7962857142857143
Classification Report               precision    recall  f1-score   support

           0       0.00      0.00      0.00      1426
           1       0.80      1.00      0.89      5574

    accuracy                           0.80      7000
   macro avg       0.40      0.50      0.44      7000
weighted avg       0.63      0.80      0.71      7000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
import joblib

joblib.dump(rf_hymodel, 'heart_model.pkl')

['rf_hymodel.pkl']